import { DonationRequest, NotificationItem, UserProfile, Connection } from '../types/lifelink';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-donor-1',
    user_id: 'donor-1',
    full_name: 'Dr. Ananya Sharma',
    role: 'donor',
    blood_group: 'O-',
    donation_types: ['blood', 'plasma', 'platelets'],
    is_available: true,
    city: 'Bengaluru',
    approx_lat: 12.978,
    approx_lng: 77.601,
    verification_status: 'verified',
    is_admin: false,
    phone: '+91 98765 43210',
    email: 'donor@lifelink.org',
    created_at: new Date(Date.now() - 86400000 * 45).toISOString(),
  },
  {
    id: 'usr-donor-2',
    user_id: 'donor-2',
    full_name: 'Vikram Malhotra',
    role: 'donor',
    blood_group: 'A+',
    donation_types: ['blood', 'organ'],
    is_available: true,
    city: 'Bengaluru',
    approx_lat: 12.935,
    approx_lng: 77.618,
    verification_status: 'verified',
    is_admin: false,
    phone: '+91 98112 34567',
    email: 'vikram.m@example.com',
    created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: 'usr-donor-3',
    user_id: 'donor-3',
    full_name: 'Kavita Reddy',
    role: 'donor',
    blood_group: 'B+',
    donation_types: ['blood', 'platelets'],
    is_available: true,
    city: 'Bengaluru',
    approx_lat: 12.926,
    approx_lng: 77.585,
    verification_status: 'verified',
    is_admin: false,
    phone: '+91 97400 12345',
    email: 'kavita.r@example.com',
    created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
  {
    id: 'usr-donor-4',
    user_id: 'donor-4',
    full_name: 'Arjun Das',
    role: 'donor',
    blood_group: 'AB+',
    donation_types: ['blood', 'plasma', 'stem_cells'],
    is_available: true,
    city: 'Bengaluru',
    approx_lat: 13.001,
    approx_lng: 77.568,
    verification_status: 'pending',
    is_admin: false,
    phone: '+91 99000 88776',
    email: 'arjun.d@example.com',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'usr-donor-5',
    user_id: 'donor-5',
    full_name: 'Pooja Iyer',
    role: 'donor',
    blood_group: 'O+',
    donation_types: ['blood', 'plasma'],
    is_available: true,
    city: 'Mumbai',
    approx_lat: 19.082,
    approx_lng: 72.885,
    verification_status: 'verified',
    is_admin: false,
    phone: '+91 98200 98200',
    email: 'pooja.i@example.com',
    created_at: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
  {
    id: 'usr-receiver-1',
    user_id: 'receiver-1',
    full_name: 'Rahul Verma',
    role: 'receiver',
    blood_group: 'B+',
    donation_types: ['blood', 'platelets'],
    is_available: true,
    city: 'Bengaluru',
    approx_lat: 12.969,
    approx_lng: 77.598,
    verification_status: 'verified',
    is_admin: false,
    phone: '+91 91234 56789',
    email: 'receiver@lifelink.org',
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'usr-admin-1',
    user_id: 'admin-1',
    full_name: 'LifeLink Moderation Desk',
    role: 'admin',
    blood_group: 'O+',
    donation_types: ['blood', 'organ'],
    is_available: true,
    city: 'Bengaluru',
    approx_lat: 12.971,
    approx_lng: 77.594,
    verification_status: 'verified',
    is_admin: true,
    phone: '+91 80 4000 1234',
    email: 'admin@lifelink.org',
    created_at: new Date(Date.now() - 86400000 * 100).toISOString(),
  },
];

export const INITIAL_REQUESTS: DonationRequest[] = [
  {
    id: 'req-1',
    receiver_id: 'usr-receiver-1',
    receiver_name: 'Rahul Verma',
    donation_type: 'blood',
    blood_group: 'B+',
    units_needed: 2,
    urgency: 'emergency',
    hospital_name: 'Manipal Hospital, Old Airport Road',
    city: 'Bengaluru',
    approx_lat: 12.959,
    approx_lng: 77.652,
    notes: 'Urgent bypass surgery scheduled in 3 hours. Need 2 units of compatible whole blood urgently.',
    status: 'open',
    verification_status: 'verified',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'req-2',
    receiver_id: 'usr-receiver-2',
    receiver_name: 'Meera Nambiar',
    donation_type: 'platelets',
    blood_group: 'O-',
    units_needed: 3,
    urgency: 'urgent',
    hospital_name: 'Aster CMI Hospital, Hebbal',
    city: 'Bengaluru',
    approx_lat: 13.058,
    approx_lng: 77.591,
    notes: 'Dengue with severe thrombocytopenia. Platelet count below 15,000.',
    status: 'open',
    verification_status: 'verified',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'req-3',
    receiver_id: 'usr-receiver-3',
    receiver_name: 'Sunil Chetri',
    donation_type: 'plasma',
    blood_group: 'A+',
    units_needed: 1,
    urgency: 'normal',
    hospital_name: 'Fortis Hospital, Bannerghatta Road',
    city: 'Bengaluru',
    approx_lat: 12.898,
    approx_lng: 77.598,
    notes: 'Post-operative recovery plasma therapy.',
    status: 'open',
    verification_status: 'pending',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'req-4',
    receiver_id: 'usr-receiver-4',
    receiver_name: 'Suresh Patil',
    donation_type: 'blood',
    blood_group: 'AB+',
    units_needed: 2,
    urgency: 'urgent',
    hospital_name: 'Lilavati Hospital, Bandra',
    city: 'Mumbai',
    approx_lat: 19.052,
    approx_lng: 72.829,
    notes: 'Emergency accident trauma unit.',
    status: 'open',
    verification_status: 'verified',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
];

export const INITIAL_CONNECTIONS: Connection[] = [
  {
    id: 'conn-1',
    request_id: 'req-1',
    donor_id: 'usr-donor-1',
    donor_name: 'Dr. Ananya Sharma',
    donor_blood_group: 'O-',
    donor_city: 'Bengaluru',
    donor_phone: '+91 98765 43210',
    donor_email: 'donor@lifelink.org',
    receiver_id: 'usr-receiver-1',
    receiver_name: 'Rahul Verma',
    receiver_phone: '+91 91234 56789',
    receiver_email: 'receiver@lifelink.org',
    status: 'accepted',
    contact_consent_donor: true,
    contact_consent_receiver: true,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'usr-donor-1',
    title: '🚨 Emergency Blood Request within 4.2 km',
    message: 'Rahul Verma urgently needs 2 units of B+ / O- blood at Manipal Hospital.',
    type: 'emergency',
    link: '/requests/req-1',
    read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'usr-receiver-1',
    title: '🤝 Donor Connected!',
    message: 'Dr. Ananya Sharma (O-) offered to donate for your emergency request at Manipal Hospital. Contact details unlocked.',
    type: 'consent',
    link: '/requests/req-1',
    read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'notif-3',
    user_id: 'usr-donor-1',
    title: 'Verified Donor Badge Awarded',
    message: 'Your medical verification was approved. You now rank higher in emergency proximity matching.',
    type: 'system',
    link: '/profile',
    read: true,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];
