import { Report } from '../types';

export const INITIAL_DEMO_REPORTS: Report[] = [
  // Pair 1: Backpack (Lost & Found -> 94% Match)
  {
    id: 'demo-lost-1',
    userId: 'user-sarah',
    userDisplayName: 'Sarah Chen',
    userEmail: 'sarah.chen@campus.edu',
    type: 'lost',
    title: 'Black Lenovo ThinkPad Laptop Backpack',
    description: 'Black water-resistant laptop backpack with a padded compartment for 15-inch laptop. Contains a notebook and a purple pencil pouch.',
    category: 'Bags',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Backpack',
      primaryColor: 'Black',
      secondaryColors: ['Grey', 'Red'],
      brand: 'Lenovo',
      distinctiveFeatures: ['Water-resistant fabric', 'Padded laptop sleeve', 'Red accent stitch'],
      condition: 'Good',
      confidence: 0.95,
    },
    latitude: 37.7749,
    longitude: -122.4194,
    approximateLocation: 'Central Library (2nd Floor quiet study)',
    campusBuilding: 'Central Library',
    eventDate: '2026-08-21',
    eventTime: '14:30',
    contactPreference: 'in_app',
    status: 'potential_match',
    createdAt: new Date(Date.now() - 86400000 * 1.2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.2).toISOString(),
    searchKeywords: ['black', 'lenovo', 'laptop', 'backpack', 'bag', 'library', 'thinkpad'],
    isDemo: true,
  },
  {
    id: 'demo-found-1',
    userId: 'user-marcus',
    userDisplayName: 'Marcus Vance',
    userEmail: 'marcus.v@campus.edu',
    type: 'found',
    title: 'Black Lenovo Laptop Bag with red zipper tags',
    description: 'Found a black Lenovo backpack near the main entrance steps of the central library. Has a padded laptop pocket and purple stationary pouch inside.',
    category: 'Bags',
    imageUrl: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Backpack',
      primaryColor: 'Black',
      secondaryColors: ['Red'],
      brand: 'Lenovo',
      distinctiveFeatures: ['Red zipper pull tabs', 'Multiple compartments', 'Pencil case inside'],
      condition: 'Good',
      confidence: 0.96,
    },
    latitude: 37.7748,
    longitude: -122.4192,
    approximateLocation: 'Central Library (Front Entrance steps)',
    campusBuilding: 'Central Library',
    eventDate: '2026-08-21',
    eventTime: '15:15',
    contactPreference: 'in_app',
    status: 'potential_match',
    createdAt: new Date(Date.now() - 86400000 * 1.1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.1).toISOString(),
    searchKeywords: ['black', 'lenovo', 'laptop', 'backpack', 'bag', 'library', 'zipper'],
    isDemo: true,
  },

  // Pair 2: Smartphone (Lost & Found -> 92% Match)
  {
    id: 'demo-lost-2',
    userId: 'user-priya',
    userDisplayName: 'Priya Sharma',
    userEmail: 'priya.s@campus.edu',
    type: 'lost',
    title: 'Blue Samsung Galaxy S22 with cracked corner',
    description: 'Phantom Blue Samsung Galaxy smartphone in a clear case. Has a small hairline crack on the bottom-right corner of the screen glass.',
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Smartphone',
      primaryColor: 'Blue',
      secondaryColors: ['Silver'],
      brand: 'Samsung',
      model: 'Galaxy S22',
      distinctiveFeatures: ['Clear protective case', 'Cracked bottom corner glass'],
      condition: 'Cracked',
      confidence: 0.94,
    },
    latitude: 37.7739,
    longitude: -122.4205,
    approximateLocation: 'Student Cafeteria (South corner booth)',
    campusBuilding: 'Student Cafeteria',
    eventDate: '2026-08-21',
    eventTime: '12:45',
    contactPreference: 'in_app',
    status: 'potential_match',
    createdAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    searchKeywords: ['blue', 'samsung', 'galaxy', 'phone', 'smartphone', 'cafeteria', 'cracked'],
    isDemo: true,
  },
  {
    id: 'demo-found-2',
    userId: 'user-jordan',
    userDisplayName: 'Jordan Lee',
    userEmail: 'jordan.lee@campus.edu',
    type: 'found',
    title: 'Blue Samsung phone discovered on dining table',
    description: 'Turned in a blue Samsung Android phone found on a booth table after lunch rush. Transparent case, slight screen crack on bottom corner.',
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Smartphone',
      primaryColor: 'Blue',
      brand: 'Samsung',
      distinctiveFeatures: ['Transparent silicone case', 'Bottom screen crack'],
      condition: 'Cracked',
      confidence: 0.93,
    },
    latitude: 37.7740,
    longitude: -122.4204,
    approximateLocation: 'Student Cafeteria (Dining tables)',
    campusBuilding: 'Student Cafeteria',
    eventDate: '2026-08-21',
    eventTime: '13:10',
    contactPreference: 'in_app',
    status: 'potential_match',
    createdAt: new Date(Date.now() - 86400000 * 1.4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.4).toISOString(),
    searchKeywords: ['blue', 'samsung', 'phone', 'android', 'cafeteria', 'transparent', 'crack'],
    isDemo: true,
  },

  // Pair 3: Student ID Card (Lost & Found -> 96% Match)
  {
    id: 'demo-lost-3',
    userId: 'user-alex',
    userDisplayName: 'Alex Rivera',
    userEmail: 'alex.rivera@campus.edu',
    type: 'lost',
    title: 'Student ID & Keycard - Alex Rivera',
    description: 'Official university campus student ID card with magnetic stripe and photo. Name: Alex Rivera, Major: Computer Science.',
    category: 'ID/Cards',
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Student ID Card',
      primaryColor: 'White',
      secondaryColors: ['Blue', 'Gold'],
      distinctiveFeatures: ['Student photo', 'University barcode', 'Magnetic strip'],
      textFound: 'Alex Rivera Computer Science',
      condition: 'Good',
      confidence: 0.98,
    },
    latitude: 37.7758,
    longitude: -122.4182,
    approximateLocation: 'Computer Science Block (Lab 3)',
    campusBuilding: 'Computer Science Block',
    eventDate: '2026-08-22',
    eventTime: '09:15',
    contactPreference: 'in_app',
    status: 'potential_match',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    searchKeywords: ['student', 'id', 'card', 'alex', 'rivera', 'cs', 'keycard'],
    isDemo: true,
  },
  {
    id: 'demo-found-3',
    userId: 'user-staff-david',
    userDisplayName: 'David Miller (Lab Admin)',
    userEmail: 'd.miller@campus.edu',
    type: 'found',
    title: 'Found Student ID badge for Alex Rivera',
    description: 'Found an ID card on the keyboard of Station 14 in CS Lab 3. Held at lab supervisor desk.',
    category: 'ID/Cards',
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Student ID Card',
      primaryColor: 'White',
      secondaryColors: ['Blue'],
      distinctiveFeatures: ['Campus Seal', 'Student Name Alex Rivera'],
      textFound: 'Alex Rivera CS Lab',
      condition: 'Good',
      confidence: 0.99,
    },
    latitude: 37.7758,
    longitude: -122.4181,
    approximateLocation: 'Computer Science Block (Lab Supervisor Desk)',
    campusBuilding: 'Computer Science Block',
    eventDate: '2026-08-22',
    eventTime: '09:40',
    contactPreference: 'in_app',
    status: 'potential_match',
    createdAt: new Date(Date.now() - 3600000 * 3.5).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 3.5).toISOString(),
    searchKeywords: ['student', 'id', 'card', 'alex', 'rivera', 'lab', 'supervisor'],
    isDemo: true,
  },

  // Pair 4: AirPods Pro (Lost & Found -> 89% Match)
  {
    id: 'demo-lost-4',
    userId: 'user-emily',
    userDisplayName: 'Emily Taylor',
    userEmail: 'emily.t@campus.edu',
    type: 'lost',
    title: 'Apple AirPods Pro 2 in white case with frog sticker',
    description: 'AirPods Pro 2nd Gen in white case. Has a small cute green frog sticker on the front lid.',
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Wireless Earbuds',
      primaryColor: 'White',
      secondaryColors: ['Green'],
      brand: 'Apple',
      model: 'AirPods Pro',
      distinctiveFeatures: ['Green frog sticker on lid', 'Lightning port on base'],
      condition: 'Good',
      confidence: 0.93,
    },
    latitude: 37.7725,
    longitude: -122.4220,
    approximateLocation: 'Sports Complex (Bleachers area)',
    campusBuilding: 'Sports Complex & Gym',
    eventDate: '2026-08-20',
    eventTime: '17:30',
    contactPreference: 'in_app',
    status: 'active',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    searchKeywords: ['apple', 'airpods', 'earbuds', 'white', 'frog', 'sticker', 'sports', 'gym'],
    isDemo: true,
  },
  {
    id: 'demo-found-4',
    userId: 'user-coach-ben',
    userDisplayName: 'Ben Jackson',
    userEmail: 'b.jackson@campus.edu',
    type: 'found',
    title: 'White Apple AirPods case with cartoon sticker',
    description: 'Found a white wireless earbud case on the courtside bleachers. It has a green cartoon animal decal.',
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Wireless Earbuds',
      primaryColor: 'White',
      secondaryColors: ['Green'],
      brand: 'Apple',
      distinctiveFeatures: ['Green sticker', 'Earbuds inside'],
      condition: 'Good',
      confidence: 0.91,
    },
    latitude: 37.7726,
    longitude: -122.4219,
    approximateLocation: 'Sports Complex (Courtside bench)',
    campusBuilding: 'Sports Complex & Gym',
    eventDate: '2026-08-20',
    eventTime: '18:15',
    contactPreference: 'in_app',
    status: 'active',
    createdAt: new Date(Date.now() - 86400000 * 1.9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.9).toISOString(),
    searchKeywords: ['apple', 'airpods', 'case', 'sticker', 'sports', 'bleachers'],
    isDemo: true,
  },

  // Pair 5: Water Bottle (Lost & Found -> 91% Match)
  {
    id: 'demo-lost-5',
    userId: 'user-liam',
    userDisplayName: 'Liam O\'Connor',
    userEmail: 'liam.oc@campus.edu',
    type: 'lost',
    title: 'Hydro Flask 32oz Teal Insulated Flask',
    description: 'Teal/mint colored metal bottle with black flex cap. Has a NASA circular sticker and slight dent near the bottom.',
    category: 'Accessories',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Water Bottle',
      primaryColor: 'Teal',
      secondaryColors: ['Black'],
      brand: 'Hydro Flask',
      distinctiveFeatures: ['NASA sticker', 'Small bottom dent', 'Black handle cap'],
      condition: 'Good',
      confidence: 0.94,
    },
    latitude: 37.7761,
    longitude: -122.4215,
    approximateLocation: 'Engineering Complex (Hall E2)',
    campusBuilding: 'Engineering Complex',
    eventDate: '2026-08-21',
    eventTime: '11:00',
    contactPreference: 'in_app',
    status: 'active',
    createdAt: new Date(Date.now() - 86400000 * 1.3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.3).toISOString(),
    searchKeywords: ['hydro', 'flask', 'teal', 'water', 'bottle', 'engineering', 'nasa', 'sticker'],
    isDemo: true,
  },
  {
    id: 'demo-found-5',
    userId: 'user-clara',
    userDisplayName: 'Clara Oswald',
    userEmail: 'clara.o@campus.edu',
    type: 'found',
    title: 'Teal metal water bottle with NASA sticker',
    description: 'Found on the desk in Engineering lecture room E2. Teal color, metal build, space sticker attached.',
    category: 'Accessories',
    imageUrl: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Water Bottle',
      primaryColor: 'Teal',
      brand: 'Hydro Flask',
      distinctiveFeatures: ['NASA logo sticker', 'Metal construction'],
      condition: 'Good',
      confidence: 0.93,
    },
    latitude: 37.7761,
    longitude: -122.4214,
    approximateLocation: 'Engineering Complex (Lecture Room E2 Desk)',
    campusBuilding: 'Engineering Complex',
    eventDate: '2026-08-21',
    eventTime: '11:45',
    contactPreference: 'in_app',
    status: 'active',
    createdAt: new Date(Date.now() - 86400000 * 1.25).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.25).toISOString(),
    searchKeywords: ['teal', 'metal', 'water', 'bottle', 'nasa', 'sticker', 'engineering'],
    isDemo: true,
  },

  // Pair 6: Keys with Red Lanyard (Lost & Reunited example -> 93% Match)
  {
    id: 'demo-lost-6',
    userId: 'user-sam',
    userDisplayName: 'Sam Wilson',
    userEmail: 'sam.w@campus.edu',
    type: 'lost',
    title: 'Set of 3 dorm keys on Red Campus Lanyard',
    description: '3 silver keys and 1 small brass padlock key on a red lanyard with "University Athletics" print.',
    category: 'Keys',
    imageUrl: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Keys',
      primaryColor: 'Red',
      secondaryColors: ['Silver', 'Brass'],
      distinctiveFeatures: ['Red lanyard with text', '3 silver door keys', '1 small brass key'],
      condition: 'Good',
      confidence: 0.95,
    },
    latitude: 37.7765,
    longitude: -122.4170,
    approximateLocation: 'Main Campus Gate (Bicycle racks)',
    campusBuilding: 'Main Campus Gate',
    eventDate: '2026-08-19',
    eventTime: '08:30',
    contactPreference: 'in_app',
    status: 'resolved',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    searchKeywords: ['keys', 'red', 'lanyard', 'gate', 'dorm', 'athletics'],
    isDemo: true,
  },
  {
    id: 'demo-found-6',
    userId: 'user-guard',
    userDisplayName: 'Campus Security',
    userEmail: 'security@campus.edu',
    type: 'found',
    title: 'Keys with red University Athletics lanyard',
    description: 'Turned into security kiosk from the main gate bike stand. Handed back to owner.',
    category: 'Keys',
    imageUrl: 'https://images.unsplash.com/photo-1608613304899-ea8098577e38?w=800&auto=format&fit=crop&q=80',
    aiAttributes: {
      objectType: 'Keys',
      primaryColor: 'Red',
      distinctiveFeatures: ['Athletics lanyard', 'Multiple keys on ring'],
      condition: 'Good',
      confidence: 0.96,
    },
    latitude: 37.7765,
    longitude: -122.4169,
    approximateLocation: 'Main Campus Gate (Security Kiosk)',
    campusBuilding: 'Main Campus Gate',
    eventDate: '2026-08-19',
    eventTime: '09:00',
    contactPreference: 'in_app',
    status: 'resolved',
    createdAt: new Date(Date.now() - 86400000 * 2.9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    searchKeywords: ['keys', 'red', 'lanyard', 'security', 'kiosk'],
    isDemo: true,
  },
];
